### ISSUE TITLE
Add a key for clear (Recent searches) in notmuch-hello

### ISSUE THREAD

**Issue by morgandavidson** [tarsius/notmuch-transient#1]
I posted the request here because the Feature Requests page for notmuch-transient was not found (404).

Thank you so much for this very useful transient menu. Would it be possible to add a key for the `clear` widget-button in notmuch-hello?

**Comment by tarsius** [comment]
> the Feature Requests page for notmuch-transient was not found

Thanks for letting me know. I just set that up; apparently not completely.

> Would it be possible to add a key for the `clear` widget-button in notmuch-hello?

I probably won't add that, but here you go:

```elisp
(defun my-notmuch-clear-search-history ()
  (interactive)
  (when (y-or-n-p "Are you sure you want to clear the searches? ")
    (setq notmuch-search-history nil)
    (notmuch-hello-update)))

(transient-append-suffix 'notmuch-hello-mode-transient "g"
  '("r" "clear searches" my-notmuch-clear-search-history))
```

**Comment by morgandavidson** [comment]
Thank you, your code works perfectly!
