### ISSUE TITLE
Problem with notmuch-search-transient since recent packages update

### ISSUE THREAD

**Issue by renbus** [tarsius/notmuch-transient#2]
Hello,

I recently updated a bunch of emacs packages using `list-packages` (around 30 packages were updated, I don't know really know which one exactly), and since then I have an issue with notmuch and notmuch-transient. In the notmuch-hello buffer, if I press "j" for "notmuch-search-transient", I get this error:

`transient-setup: Need command, argument, ‘:info’ or ‘:info*’; got #[0 \303\302\301\300#\207 [nil tag:inbox tree notmuch-transient--search] 4 nil nil]`

I suspect it might be some version incompatibility issue, because everything was working fine before the update. Here is what I use:

Notmuch-transient: 20240805.1916
Notmuch: 20240816.2039
Transient: 20240918.1138
Emacs: 29.4

(Although for Notmuch, if I do `M-x find-library notmuch`, it does open my OS packaged version from /usr/share/emacs/site-lisp/notmuch.el, so I'm not sure which one is loaded up.)

Thanks for your support!

**Comment by tarsius** [comment]
I suspect this is one of those issues that can be fixed by doing the re-installation dance. Uninstall all involved packages. Exit Emacs. Restart Emacs. Re-install packages.

**Comment by renbus** [comment]
Hello,

Sorry for not coming back to this earlier, I've been busy with other things... So far I haven't manage to fix this. Here is what I've tried:

- Exit Emacs
- Delete the /elpa/ directory as well as the "eln-cache" directory
- Restart Emacs.

Everything is re-downloaded, re-installed, and the problem remains.

So I kept trying different setups. I found one way that works, which is to use the builtin transient from my Emacs 29.4, which is version 0.4.3. I had to set this up manually, because since notmuch-transient depends on transient 0.7.6, which is available on GNU Elpa, the list-packages interface wouldn't let me do this. So I install Notmuch-transient through the "list-packages" interface, which automatically update the transient package, then close Emacs, then delete the "transient-..." folder under "/elpa/", as well as the transient file under the "eln-cache" folder. I restart Emacs, and now the `notmuch-search-transient` command works. If I do describe-package transient, I see that I'm not using the bultin version, v0.4.3. If I try again to install the transient package from GNU ELPA (0.7.6), or the latest one from MELPA (which is a different versioning scheme), then the `notmuch-search-transient` command stop working again, giving me the same error mentioned in my first message:

transient-setup: Need command, argument, ‘:info’ or ‘:info*’; got #[0 \303\302\301\300#\207 [nil tag:inbox tree notmuch-transient--search] 4 nil nil]

Do you have any idea why I can't use a recent Transient version?

**Comment by tarsius** [comment]
This was a regression in v0.7.6. I've pushed a new release. Thanks for the report!
